// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxOkjWHnbnGX7DEvUjNTpR1KUM2bQUqA',
    appId: '1:282590163423:web:617b0d51aa0e0150d7946a',
    messagingSenderId: '282590163423',
    projectId: 'pintarhidroponik',
    authDomain: 'pintarhidroponik.firebaseapp.com',
    storageBucket: 'pintarhidroponik.firebasestorage.app',
    measurementId: 'G-F2FCQMMBCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy9upxm9FbtQEUAcSDAnZ4HGM0Voi3cbM',
    appId: '1:282590163423:android:efe51197123fea54d7946a',
    messagingSenderId: '282590163423',
    projectId: 'pintarhidroponik',
    storageBucket: 'pintarhidroponik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmekYKqHkB3poC50gWJQ44lndNZLhjAeE',
    appId: '1:282590163423:ios:75443c8937cebd6dd7946a',
    messagingSenderId: '282590163423',
    projectId: 'pintarhidroponik',
    storageBucket: 'pintarhidroponik.firebasestorage.app',
    iosBundleId: 'com.example.pintarHidroponik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOxOkjWHnbnGX7DEvUjNTpR1KUM2bQUqA',
    appId: '1:282590163423:web:4256478610829bb4d7946a',
    messagingSenderId: '282590163423',
    projectId: 'pintarhidroponik',
    authDomain: 'pintarhidroponik.firebaseapp.com',
    storageBucket: 'pintarhidroponik.firebasestorage.app',
    measurementId: 'G-K3JBEEB43W',
  );
}
